In [5]:
# import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import os
os.chdir('F:\\')
print(os.getcwd())

F:\

In [8]:
# get file paths in a list
file_paths = [r'F:\ML Project\Singapore Resale Flat Prices Predicting\1.csv',
              r'F:\ML Project\Singapore Resale Flat Prices Predicting\2.csv',
              r'F:\ML Project\Singapore Resale Flat Prices Predicting\3.csv',
              r'F:\ML Project\Singapore Resale Flat Prices Predicting\4.csv',
              r'F:\ML Project\Singapore Resale Flat Prices Predicting\5.csv'
             ]
# declare an empty list
dfs = []
# append each csv to the dfs list
for file_path in file_paths:
    df = pd.read_csv(file_path)
    dfs.append(df)
# combine them using concat
combined_df = pd.concat(dfs, ignore_index=True)

In [9]:
# display the combined dataframe
combined_df

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease
0,1990-01,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,10 TO 12,31.0,IMPROVED,1977,9000.0,NaN
1,1990-01,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,04 TO 06,31.0,IMPROVED,1977,6000.0,NaN
2,1990-01,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,10 TO 12,31.0,IMPROVED,1977,8000.0,NaN
3,1990-01,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,07 TO 09,31.0,IMPROVED,1977,6000.0,NaN
4,1990-01,ANG MO KIO,3 ROOM,216,ANG MO KIO AVE 1,04 TO 06,73.0,NEW GENERATION,1976,47200.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
912886,2023-05,YISHUN,EXECUTIVE,827,YISHUN ST 81,01 TO 03,154.0,Maisonette,1987,829000.0,63 years 06 months
912887,2023-05,YISHUN,EXECUTIVE,824,YISHUN ST 81,07 TO 09,146.0,Maisonette,1987,855000.0,63 years 06 months
912888,2023-07,YISHUN,EXECUTIVE,837,YISHUN ST 81,01 TO 03,146.0,Maisonette,1988,860000.0,63 years 07 months
912889,2023-01,YISHUN,MULTI-GENERATION,666,YISHUN AVE 4,07 TO 09,179.0,Multi Generation,1987,1080000.0,63 years 11 months
912890,2023-06,YISHUN,MULTI-GENERATION,633,YISHUN ST 61,04 TO 06,159.0,Multi Generation,1987,935000.0,63 years 06 months

In [10]:
# check for null values
combined_df.isnull().sum()

month                       0
town                        0
flat_type                   0
block                       0
street_name                 0
storey_range                0
floor_area_sqm              0
flat_model                  0
lease_commence_date         0
resale_price                0
remaining_lease        709050
dtype: int64

In [11]:
# check the number of streets
street_nos = len(combined_df['street_name'].unique())
street_nos

583

In [12]:
# list unique street names
streets = combined_df['street_name'].unique()
streets

array(['ANG MO KIO AVE 1', 'ANG MO KIO AVE 3', 'ANG MO KIO AVE 4',
       'ANG MO KIO AVE 10', 'ANG MO KIO AVE 5', 'ANG MO KIO AVE 8',
       'ANG MO KIO AVE 6', 'ANG MO KIO AVE 9', 'ANG MO KIO AVE 2',
       'BEDOK RESERVOIR RD', 'BEDOK NTH ST 3', 'BEDOK STH RD',
       'NEW UPP CHANGI RD', 'BEDOK NTH RD', 'BEDOK STH AVE 1',
       'CHAI CHEE RD', 'CHAI CHEE DR', 'BEDOK NTH AVE 4',
       'BEDOK STH AVE 3', 'BEDOK STH AVE 2', 'BEDOK NTH ST 2',
       'BEDOK NTH ST 4', 'BEDOK NTH AVE 2', 'BEDOK NTH AVE 3',
       'BEDOK NTH AVE 1', 'BEDOK NTH ST 1', 'CHAI CHEE ST', 'SIN MING RD',
       'SHUNFU RD', 'BT BATOK ST 11', 'BT BATOK WEST AVE 8',
       'BT BATOK WEST AVE 6', 'BT BATOK ST 21', 'BT BATOK EAST AVE 5',
       'BT BATOK EAST AVE 4', 'HILLVIEW AVE', 'BT BATOK CTRL',
       'BT BATOK ST 31', 'BT BATOK EAST AVE 3', 'TAMAN HO SWEE',
       'TELOK BLANGAH CRES', 'BEO CRES', 'TELOK BLANGAH DR', 'DEPOT RD',
       'TELOK BLANGAH RISE', 'JLN BT MERAH', 'HENDERSON RD', 'INDUS RD',
       'BT MERAH VIEW', 'HENDERSON CRES', 'BT PURMEI RD',
       'TELOK BLANGAH HTS', 'EVERTON PK', 'KG BAHRU HILL', 'REDHILL CL',
       'HOY FATT RD', 'HAVELOCK RD', 'JLN KLINIK', 'JLN RUMAH TINGGI',
       'JLN BT HO SWEE', 'KIM CHENG ST', 'MOH GUAN TER',
       'TELOK BLANGAH WAY', 'KIM TIAN RD', 'KIM TIAN PL', 'EMPRESS RD',
       "QUEEN'S RD", 'FARRER RD', 'JLN KUKOH', 'OUTRAM PK', 'SHORT ST',
       'SELEGIE RD', 'UPP CROSS ST', 'WATERLOO ST', 'QUEEN ST',
       'BUFFALO RD', 'ROWELL RD', 'ROCHOR RD', 'BAIN ST', 'SMITH ST',
       'VEERASAMY RD', 'TECK WHYE AVE', 'TECK WHYE LANE',
       'CLEMENTI AVE 3', 'WEST COAST DR', 'CLEMENTI AVE 2',
       'CLEMENTI AVE 5', 'CLEMENTI AVE 4', 'CLEMENTI AVE 1',
       'WEST COAST RD', 'CLEMENTI WEST ST 1', 'CLEMENTI WEST ST 2',
       'CLEMENTI ST 13', "C'WEALTH AVE WEST", 'CLEMENTI AVE 6',
       'CLEMENTI ST 14', 'CIRCUIT RD', 'MACPHERSON LANE',
       'JLN PASAR BARU', 'GEYLANG SERAI', 'EUNOS CRES', 'SIMS DR',
       'ALJUNIED CRES', 'GEYLANG EAST AVE 1', 'DAKOTA CRES', 'PINE CL',
       'HAIG RD', 'BALAM RD', 'JLN DUA', 'GEYLANG EAST CTRL',
       'EUNOS RD 5', 'HOUGANG AVE 3', 'HOUGANG AVE 5', 'HOUGANG AVE 1',
       'HOUGANG ST 22', 'HOUGANG AVE 10', 'LOR AH SOO', 'HOUGANG ST 11',
       'HOUGANG AVE 7', 'HOUGANG ST 21', 'TEBAN GDNS RD',
       'JURONG EAST AVE 1', 'JURONG EAST ST 32', 'JURONG EAST ST 13',
       'JURONG EAST ST 21', 'JURONG EAST ST 24', 'JURONG EAST ST 31',
       'PANDAN GDNS', 'YUNG KUANG RD', 'HO CHING RD', 'HU CHING RD',
       'BOON LAY DR', 'BOON LAY AVE', 'BOON LAY PL', 'JURONG WEST ST 52',
       'JURONG WEST ST 41', 'JURONG WEST AVE 1', 'JURONG WEST ST 42',
       'JLN BATU', "ST. GEORGE'S RD", 'NTH BRIDGE RD', 'FRENCH RD',
       'BEACH RD', 'WHAMPOA DR', 'UPP BOON KENG RD', 'BENDEMEER RD',
       'WHAMPOA WEST', 'LOR LIMAU', 'KALLANG BAHRU', 'GEYLANG BAHRU',
       'DORSET RD', 'OWEN RD', 'KG ARANG RD', 'JLN BAHAGIA',
       'MOULMEIN RD', 'TOWNER RD', 'JLN RAJAH', 'KENT RD', 'AH HOOD RD',
       "KING GEORGE'S AVE", 'CRAWFORD LANE', 'MARINE CRES', 'MARINE DR',
       'MARINE TER', "C'WEALTH CL", "C'WEALTH DR", 'TANGLIN HALT RD',
       "C'WEALTH CRES", 'DOVER RD', 'MARGARET DR', 'GHIM MOH RD',
       'DOVER CRES', 'STIRLING RD', 'MEI LING ST', 'HOLLAND CL',
       'HOLLAND AVE', 'HOLLAND DR', 'DOVER CL EAST',
       'SELETAR WEST FARMWAY 6', 'LOR LEW LIAN', 'SERANGOON NTH AVE 1',
       'SERANGOON AVE 2', 'SERANGOON AVE 4', 'SERANGOON CTRL',
       'TAMPINES ST 11', 'TAMPINES ST 21', 'TAMPINES ST 91',
       'TAMPINES ST 81', 'TAMPINES AVE 4', 'TAMPINES ST 22',
       'TAMPINES ST 12', 'TAMPINES ST 23', 'TAMPINES ST 24',
       'TAMPINES ST 41', 'TAMPINES ST 82', 'TAMPINES ST 83',
       'TAMPINES AVE 5', 'LOR 2 TOA PAYOH', 'LOR 8 TOA PAYOH',
       'LOR 1 TOA PAYOH', 'LOR 5 TOA PAYOH', 'LOR 3 TOA PAYOH',
       'LOR 7 TOA PAYOH', 'TOA PAYOH EAST', 'LOR 4 TOA PAYOH',
       'TOA PAYOH CTRL', 'TOA PAYOH NTH', 'POTONG PASIR AVE 3',
       'POTONG PASIR AVE 1', 'UPP ALJUNIED LANE', 'JOO SENG RD',
       'MARSILING LANE', 'MARSILING DR', 'MARSILING RISE',
       'MARSILING CRES', 'WOODLANDS CTR RD', 'WOODLANDS ST 13',
       'WOODLANDS ST 11', 'YISHUN RING RD', 'YISHUN AVE 5',
       'YISHUN ST 72', 'YISHUN ST 11', 'YISHUN ST 21', 'YISHUN ST 22',
       'YISHUN AVE 3', 'CHAI CHEE AVE', 'ZION RD', 'LENGKOK BAHRU',
       'SPOTTISWOODE PK RD', 'NEW MKT RD', 'TG PAGAR PLAZA',
       'KELANTAN RD', 'PAYA LEBAR WAY', 'UBI AVE 1', 'SIMS AVE',
       'YUNG PING RD', 'TAO CHING RD', 'GLOUCESTER RD', 'BOON KENG RD',
       'WHAMPOA STH', 'CAMBRIDGE RD', 'TAMPINES ST 42', 'LOR 6 TOA PAYOH',
       'KIM KEAT AVE', 'YISHUN AVE 6', 'YISHUN AVE 9', 'YISHUN ST 71',
       'BT BATOK ST 32', 'SILAT AVE', 'TIONG BAHRU RD', 'SAGO LANE',
       "ST. GEORGE'S LANE", 'LIM CHU KANG RD', "C'WEALTH AVE",
       "QUEEN'S CL", 'SERANGOON AVE 3', 'POTONG PASIR AVE 2',
       'WOODLANDS AVE 1', 'YISHUN AVE 4', 'LOWER DELTA RD', 'NILE RD',
       'JLN MEMBINA BARAT', 'JLN BERSEH', 'CHANDER RD', 'CASSIA CRES',
       'OLD AIRPORT RD', 'ALJUNIED RD', 'BUANGKOK STH FARMWAY 1',
       'BT BATOK ST 33', 'ALEXANDRA RD', 'CHIN SWEE RD', 'SIMS PL',
       'HOUGANG AVE 2', 'HOUGANG AVE 8', 'SEMBAWANG RD', 'SIMEI ST 1',
       'BT BATOK ST 34', 'BT MERAH CTRL', 'LIM LIAK ST', 'JLN TENTERAM',
       'WOODLANDS ST 32', 'SIN MING AVE', 'BT BATOK ST 52', 'DELTA AVE',
       'PIPIT RD', 'HOUGANG AVE 4', 'QUEENSWAY', 'YISHUN ST 61',
       'BISHAN ST 12', "JLN MA'MOR", 'TAMPINES ST 44', 'TAMPINES ST 43',
       'BISHAN ST 13', 'JLN DUSUN', 'YISHUN AVE 2', 'JOO CHIAT RD',
       'EAST COAST RD', 'REDHILL RD', 'KIM PONG RD', 'RACE COURSE RD',
       'KRETA AYER RD', 'HOUGANG ST 61', 'TESSENSOHN RD', 'MARSILING RD',
       'YISHUN ST 81', 'BT BATOK ST 51', 'BT BATOK WEST AVE 4',
       'BT BATOK WEST AVE 2', 'JURONG WEST ST 91', 'JURONG WEST ST 81',
       'GANGSA RD', 'MCNAIR RD', 'SIMEI ST 4', 'YISHUN AVE 7',
       'SERANGOON NTH AVE 2', 'YISHUN AVE 11', 'BANGKIT RD',
       'JURONG WEST ST 73', 'OUTRAM HILL', 'HOUGANG AVE 6',
       'PASIR RIS ST 12', 'PENDING RD', 'PETIR RD', 'LOR 3 GEYLANG',
       'BISHAN ST 11', 'PASIR RIS DR 6', 'BISHAN ST 23',
       'JURONG WEST ST 92', 'PASIR RIS ST 11', 'YISHUN CTRL',
       'BISHAN ST 22', 'SIMEI RD', 'TAMPINES ST 84', 'BT PANJANG RING RD',
       'JURONG WEST ST 93', 'FAJAR RD', 'WOODLANDS ST 81',
       'CHOA CHU KANG CTRL', 'PASIR RIS ST 51', 'HOUGANG ST 52',
       'CASHEW RD', 'TOH YI DR', 'HOUGANG CTRL', 'KG KAYU RD',
       'TAMPINES AVE 8', 'TAMPINES ST 45', 'SIMEI ST 2',
       'WOODLANDS AVE 3', 'LENGKONG TIGA', 'WOODLANDS ST 82',
       'SERANGOON NTH AVE 4', 'SERANGOON CTRL DR', 'BRIGHT HILL DR',
       'SAUJANA RD', 'CHOA CHU KANG AVE 3', 'TAMPINES AVE 9',
       'JURONG WEST ST 51', 'YUNG HO RD', 'SERANGOON AVE 1',
       'PASIR RIS ST 41', 'GEYLANG EAST AVE 2', 'CHOA CHU KANG AVE 2',
       'KIM KEAT LINK', 'PASIR RIS DR 4', 'PASIR RIS ST 21',
       'SENG POH RD', 'HOUGANG ST 51', 'JURONG WEST ST 72',
       'JURONG WEST ST 71', 'PASIR RIS ST 52', 'TAMPINES ST 32',
       'CHOA CHU KANG AVE 4', 'CHOA CHU KANG LOOP', 'JLN TENAGA',
       'TAMPINES CTRL 1', 'TAMPINES ST 33', 'BT BATOK WEST AVE 7',
       'JURONG WEST AVE 5', 'TAMPINES AVE 7', 'WOODLANDS ST 83',
       'CHOA CHU KANG ST 51', 'PASIR RIS DR 3', 'YISHUN CTRL 1',
       'CHOA CHU KANG AVE 1', 'WOODLANDS ST 31', 'BT MERAH LANE 1',
       'PASIR RIS ST 13', 'ELIAS RD', 'BISHAN ST 24', 'WHAMPOA RD',
       'WOODLANDS ST 41', 'PASIR RIS ST 71', 'JURONG WEST ST 74',
       'PASIR RIS DR 1', 'PASIR RIS ST 72', 'PASIR RIS DR 10',
       'CHOA CHU KANG ST 52', 'CLARENCE LANE', 'CHOA CHU KANG NTH 6',
       'PASIR RIS ST 53', 'CHOA CHU KANG NTH 5', 'ANG MO KIO ST 21',
       'JLN DAMAI', 'CHOA CHU KANG ST 62', 'WOODLANDS AVE 5',
       'WOODLANDS DR 50', 'CHOA CHU KANG ST 53', 'TAMPINES ST 72',
       'UPP SERANGOON RD', 'JURONG WEST ST 75', 'STRATHMORE AVE',
       'ANG MO KIO ST 31', 'TAMPINES ST 34', 'YUNG AN RD',
       'WOODLANDS AVE 4', 'CHOA CHU KANG NTH 7', 'ANG MO KIO ST 11',
       'WOODLANDS AVE 9', 'YUNG LOH RD', 'CHOA CHU KANG DR',
       'CHOA CHU KANG ST 54', 'REDHILL LANE', 'KANG CHING RD',
       'TAH CHING RD', 'SIMEI ST 5', 'WOODLANDS DR 40', 'WOODLANDS DR 70',
       'TAMPINES ST 71', 'WOODLANDS DR 42', 'SERANGOON NTH AVE 3',
       'JELAPANG RD', 'BT BATOK ST 22', 'HOUGANG ST 91',
       'WOODLANDS AVE 6', 'WOODLANDS CIRCLE', 'CORPORATION DR',
       'LOMPANG RD', 'WOODLANDS DR 72', 'CHOA CHU KANG ST 64',
       'BT BATOK ST 24', 'JLN TECK WHYE', 'WOODLANDS CRES',
       'WOODLANDS DR 60', 'CHANGI VILLAGE RD', 'BT BATOK ST 25',
       'HOUGANG AVE 9', 'JURONG WEST CTRL 1', 'WOODLANDS RING RD',
       'CHOA CHU KANG AVE 5', 'TOH GUAN RD', 'JURONG WEST ST 61',
       'WOODLANDS DR 14', 'HOUGANG ST 92', 'CHOA CHU KANG CRES',
       'SEMBAWANG CL', 'CANBERRA RD', 'SEMBAWANG CRES', 'SEMBAWANG VISTA',
       'COMPASSVALE WALK', 'RIVERVALE ST', 'WOODLANDS DR 62',
       'SEMBAWANG DR', 'WOODLANDS DR 53', 'WOODLANDS DR 52',
       'RIVERVALE WALK', 'COMPASSVALE LANE', 'RIVERVALE DR', 'SENJA RD',
       'JURONG WEST ST 65', 'RIVERVALE CRES', 'WOODLANDS DR 44',
       'COMPASSVALE DR', 'WOODLANDS DR 16', 'COMPASSVALE RD',
       'WOODLANDS DR 73', 'HOUGANG ST 31', 'JURONG WEST ST 64',
       'WOODLANDS DR 71', 'YISHUN ST 20', 'ADMIRALTY DR',
       'COMPASSVALE ST', 'BEDOK RESERVOIR VIEW', 'YUNG SHENG RD',
       'ADMIRALTY LINK', 'SENGKANG EAST WAY', 'ANG MO KIO ST 32',
       'ANG MO KIO ST 52', 'BOON TIONG RD', 'JURONG WEST ST 62',
       'ANCHORVALE LINK', 'CANBERRA LINK', 'COMPASSVALE CRES',
       'CLEMENTI ST 12', 'MONTREAL DR', 'WELLINGTON CIRCLE',
       'SENGKANG EAST RD', 'JURONG WEST AVE 3', 'ANCHORVALE LANE',
       'SENJA LINK', 'EDGEFIELD PLAINS', 'ANCHORVALE DR', 'SEGAR RD',
       'FARRER PK RD', 'PUNGGOL FIELD', 'EDGEDALE PLAINS',
       'ANCHORVALE RD', 'CANTONMENT CL', 'JLN MEMBINA', 'FERNVALE LANE',
       'JURONG WEST ST 25', 'CLEMENTI ST 11', 'PUNGGOL FIELD WALK',
       'KLANG LANE', 'PUNGGOL CTRL', 'JELEBU RD', 'BUANGKOK CRES',
       'WOODLANDS DR 75', 'BT BATOK WEST AVE 5', 'JELLICOE RD',
       'PUNGGOL DR', 'JURONG WEST ST 24', 'SEMBAWANG WAY', 'FERNVALE RD',
       'BUANGKOK LINK', 'FERNVALE LINK', 'JLN TIGA', 'YUAN CHING RD',
       'COMPASSVALE LINK', 'MARINE PARADE CTRL', 'COMPASSVALE BOW',
       'PUNGGOL RD', 'BEDOK CTRL', 'PUNGGOL EAST', 'SENGKANG CTRL',
       'TAMPINES CTRL 7', 'SENGKANG WEST AVE', 'PUNGGOL PL',
       'CANTONMENT RD', 'GHIM MOH LINK', 'SIMEI LANE', 'YISHUN ST 41',
       'TELOK BLANGAH ST 31', 'JLN KAYU', 'LOR 1A TOA PAYOH',
       'PUNGGOL WALK', 'SENGKANG WEST WAY', 'BUANGKOK GREEN',
       'PUNGGOL WAY', 'YISHUN ST 31', 'TECK WHYE CRES', 'MONTREAL LINK',
       'UPP SERANGOON CRES', 'SUMANG LINK', 'SENGKANG EAST AVE',
       'YISHUN AVE 1', 'ANCHORVALE CRES', 'ANCHORVALE ST',
       'TAMPINES CTRL 8', 'YISHUN ST 51', 'UPP SERANGOON VIEW',
       'TAMPINES AVE 1', 'BEDOK RESERVOIR CRES', 'ANG MO KIO ST 61',
       'DAWSON RD', 'FERNVALE ST', 'HOUGANG ST 32', 'TAMPINES ST 86',
       'SUMANG WALK', 'CHOA CHU KANG AVE 7', 'KEAT HONG CL',
       'JURONG WEST CTRL 3', 'KEAT HONG LINK', 'ALJUNIED AVE 2',
       'CANBERRA CRES', 'SUMANG LANE', 'CANBERRA ST', 'ANG MO KIO ST 44',
       'WOODLANDS RISE', 'CANBERRA WALK', 'ANG MO KIO ST 51',
       'BT BATOK EAST AVE 6', 'BT BATOK WEST AVE 9', 'TAMPINES ST 61'],
      dtype=object)

In [13]:
# map the streets to povide input to ML model
streets_mapping = {street: idx + 1 for idx, street in enumerate(streets)}
streets_mapping

{'ANG MO KIO AVE 1': 1,
 'ANG MO KIO AVE 3': 2,
 'ANG MO KIO AVE 4': 3,
 'ANG MO KIO AVE 10': 4,
 'ANG MO KIO AVE 5': 5,
 'ANG MO KIO AVE 8': 6,
 'ANG MO KIO AVE 6': 7,
 'ANG MO KIO AVE 9': 8,
 'ANG MO KIO AVE 2': 9,
 'BEDOK RESERVOIR RD': 10,
 'BEDOK NTH ST 3': 11,
 'BEDOK STH RD': 12,
 'NEW UPP CHANGI RD': 13,
 'BEDOK NTH RD': 14,
 'BEDOK STH AVE 1': 15,
 'CHAI CHEE RD': 16,
 'CHAI CHEE DR': 17,
 'BEDOK NTH AVE 4': 18,
 'BEDOK STH AVE 3': 19,
 'BEDOK STH AVE 2': 20,
 'BEDOK NTH ST 2': 21,
 'BEDOK NTH ST 4': 22,
 'BEDOK NTH AVE 2': 23,
 'BEDOK NTH AVE 3': 24,
 'BEDOK NTH AVE 1': 25,
 'BEDOK NTH ST 1': 26,
 'CHAI CHEE ST': 27,
 'SIN MING RD': 28,
 'SHUNFU RD': 29,
 'BT BATOK ST 11': 30,
 'BT BATOK WEST AVE 8': 31,
 'BT BATOK WEST AVE 6': 32,
 'BT BATOK ST 21': 33,
 'BT BATOK EAST AVE 5': 34,
 'BT BATOK EAST AVE 4': 35,
 'HILLVIEW AVE': 36,
 'BT BATOK CTRL': 37,
 'BT BATOK ST 31': 38,
 'BT BATOK EAST AVE 3': 39,
 'TAMAN HO SWEE': 40,
 'TELOK BLANGAH CRES': 41,
 'BEO CRES': 42,
 'TELOK BLANGAH DR': 43,
 'DEPOT RD': 44,
 'TELOK BLANGAH RISE': 45,
 'JLN BT MERAH': 46,
 'HENDERSON RD': 47,
 'INDUS RD': 48,
 'BT MERAH VIEW': 49,
 'HENDERSON CRES': 50,
 'BT PURMEI RD': 51,
 'TELOK BLANGAH HTS': 52,
 'EVERTON PK': 53,
 'KG BAHRU HILL': 54,
 'REDHILL CL': 55,
 'HOY FATT RD': 56,
 'HAVELOCK RD': 57,
 'JLN KLINIK': 58,
 'JLN RUMAH TINGGI': 59,
 'JLN BT HO SWEE': 60,
 'KIM CHENG ST': 61,
 'MOH GUAN TER': 62,
 'TELOK BLANGAH WAY': 63,
 'KIM TIAN RD': 64,
 'KIM TIAN PL': 65,
 'EMPRESS RD': 66,
 "QUEEN'S RD": 67,
 'FARRER RD': 68,
 'JLN KUKOH': 69,
 'OUTRAM PK': 70,
 'SHORT ST': 71,
 'SELEGIE RD': 72,
 'UPP CROSS ST': 73,
 'WATERLOO ST': 74,
 'QUEEN ST': 75,
 'BUFFALO RD': 76,
 'ROWELL RD': 77,
 'ROCHOR RD': 78,
 'BAIN ST': 79,
 'SMITH ST': 80,
 'VEERASAMY RD': 81,
 'TECK WHYE AVE': 82,
 'TECK WHYE LANE': 83,
 'CLEMENTI AVE 3': 84,
 'WEST COAST DR': 85,
 'CLEMENTI AVE 2': 86,
 'CLEMENTI AVE 5': 87,
 'CLEMENTI AVE 4': 88,
 'CLEMENTI AVE 1': 89,
 'WEST COAST RD': 90,
 'CLEMENTI WEST ST 1': 91,
 'CLEMENTI WEST ST 2': 92,
 'CLEMENTI ST 13': 93,
 "C'WEALTH AVE WEST": 94,
 'CLEMENTI AVE 6': 95,
 'CLEMENTI ST 14': 96,
 'CIRCUIT RD': 97,
 'MACPHERSON LANE': 98,
 'JLN PASAR BARU': 99,
 'GEYLANG SERAI': 100,
 'EUNOS CRES': 101,
 'SIMS DR': 102,
 'ALJUNIED CRES': 103,
 'GEYLANG EAST AVE 1': 104,
 'DAKOTA CRES': 105,
 'PINE CL': 106,
 'HAIG RD': 107,
 'BALAM RD': 108,
 'JLN DUA': 109,
 'GEYLANG EAST CTRL': 110,
 'EUNOS RD 5': 111,
 'HOUGANG AVE 3': 112,
 'HOUGANG AVE 5': 113,
 'HOUGANG AVE 1': 114,
 'HOUGANG ST 22': 115,
 'HOUGANG AVE 10': 116,
 'LOR AH SOO': 117,
 'HOUGANG ST 11': 118,
 'HOUGANG AVE 7': 119,
 'HOUGANG ST 21': 120,
 'TEBAN GDNS RD': 121,
 'JURONG EAST AVE 1': 122,
 'JURONG EAST ST 32': 123,
 'JURONG EAST ST 13': 124,
 'JURONG EAST ST 21': 125,
 'JURONG EAST ST 24': 126,
 'JURONG EAST ST 31': 127,
 'PANDAN GDNS': 128,
 'YUNG KUANG RD': 129,
 'HO CHING RD': 130,
 'HU CHING RD': 131,
 'BOON LAY DR': 132,
 'BOON LAY AVE': 133,
 'BOON LAY PL': 134,
 'JURONG WEST ST 52': 135,
 'JURONG WEST ST 41': 136,
 'JURONG WEST AVE 1': 137,
 'JURONG WEST ST 42': 138,
 'JLN BATU': 139,
 "ST. GEORGE'S RD": 140,
 'NTH BRIDGE RD': 141,
 'FRENCH RD': 142,
 'BEACH RD': 143,
 'WHAMPOA DR': 144,
 'UPP BOON KENG RD': 145,
 'BENDEMEER RD': 146,
 'WHAMPOA WEST': 147,
 'LOR LIMAU': 148,
 'KALLANG BAHRU': 149,
 'GEYLANG BAHRU': 150,
 'DORSET RD': 151,
 'OWEN RD': 152,
 'KG ARANG RD': 153,
 'JLN BAHAGIA': 154,
 'MOULMEIN RD': 155,
 'TOWNER RD': 156,
 'JLN RAJAH': 157,
 'KENT RD': 158,
 'AH HOOD RD': 159,
 "KING GEORGE'S AVE": 160,
 'CRAWFORD LANE': 161,
 'MARINE CRES': 162,
 'MARINE DR': 163,
 'MARINE TER': 164,
 "C'WEALTH CL": 165,
 "C'WEALTH DR": 166,
 'TANGLIN HALT RD': 167,
 "C'WEALTH CRES": 168,
 'DOVER RD': 169,
 'MARGARET DR': 170,
 'GHIM MOH RD': 171,
 'DOVER CRES': 172,
 'STIRLING RD': 173,
 'MEI LING ST': 174,
 'HOLLAND CL': 175,
 'HOLLAND AVE': 176,
 'HOLLAND DR': 177,
 'DOVER CL EAST': 178,
 'SELETAR WEST FARMWAY 6': 179,
 'LOR LEW LIAN': 180,
 'SERANGOON NTH AVE 1': 181,
 'SERANGOON AVE 2': 182,
 'SERANGOON AVE 4': 183,
 'SERANGOON CTRL': 184,
 'TAMPINES ST 11': 185,
 'TAMPINES ST 21': 186,
 'TAMPINES ST 91': 187,
 'TAMPINES ST 81': 188,
 'TAMPINES AVE 4': 189,
 'TAMPINES ST 22': 190,
 'TAMPINES ST 12': 191,
 'TAMPINES ST 23': 192,
 'TAMPINES ST 24': 193,
 'TAMPINES ST 41': 194,
 'TAMPINES ST 82': 195,
 'TAMPINES ST 83': 196,
 'TAMPINES AVE 5': 197,
 'LOR 2 TOA PAYOH': 198,
 'LOR 8 TOA PAYOH': 199,
 'LOR 1 TOA PAYOH': 200,
 'LOR 5 TOA PAYOH': 201,
 'LOR 3 TOA PAYOH': 202,
 'LOR 7 TOA PAYOH': 203,
 'TOA PAYOH EAST': 204,
 'LOR 4 TOA PAYOH': 205,
 'TOA PAYOH CTRL': 206,
 'TOA PAYOH NTH': 207,
 'POTONG PASIR AVE 3': 208,
 'POTONG PASIR AVE 1': 209,
 'UPP ALJUNIED LANE': 210,
 'JOO SENG RD': 211,
 'MARSILING LANE': 212,
 'MARSILING DR': 213,
 'MARSILING RISE': 214,
 'MARSILING CRES': 215,
 'WOODLANDS CTR RD': 216,
 'WOODLANDS ST 13': 217,
 'WOODLANDS ST 11': 218,
 'YISHUN RING RD': 219,
 'YISHUN AVE 5': 220,
 'YISHUN ST 72': 221,
 'YISHUN ST 11': 222,
 'YISHUN ST 21': 223,
 'YISHUN ST 22': 224,
 'YISHUN AVE 3': 225,
 'CHAI CHEE AVE': 226,
 'ZION RD': 227,
 'LENGKOK BAHRU': 228,
 'SPOTTISWOODE PK RD': 229,
 'NEW MKT RD': 230,
 'TG PAGAR PLAZA': 231,
 'KELANTAN RD': 232,
 'PAYA LEBAR WAY': 233,
 'UBI AVE 1': 234,
 'SIMS AVE': 235,
 'YUNG PING RD': 236,
 'TAO CHING RD': 237,
 'GLOUCESTER RD': 238,
 'BOON KENG RD': 239,
 'WHAMPOA STH': 240,
 'CAMBRIDGE RD': 241,
 'TAMPINES ST 42': 242,
 'LOR 6 TOA PAYOH': 243,
 'KIM KEAT AVE': 244,
 'YISHUN AVE 6': 245,
 'YISHUN AVE 9': 246,
 'YISHUN ST 71': 247,
 'BT BATOK ST 32': 248,
 'SILAT AVE': 249,
 'TIONG BAHRU RD': 250,
 'SAGO LANE': 251,
 "ST. GEORGE'S LANE": 252,
 'LIM CHU KANG RD': 253,
 "C'WEALTH AVE": 254,
 "QUEEN'S CL": 255,
 'SERANGOON AVE 3': 256,
 'POTONG PASIR AVE 2': 257,
 'WOODLANDS AVE 1': 258,
 'YISHUN AVE 4': 259,
 'LOWER DELTA RD': 260,
 'NILE RD': 261,
 'JLN MEMBINA BARAT': 262,
 'JLN BERSEH': 263,
 'CHANDER RD': 264,
 'CASSIA CRES': 265,
 'OLD AIRPORT RD': 266,
 'ALJUNIED RD': 267,
 'BUANGKOK STH FARMWAY 1': 268,
 'BT BATOK ST 33': 269,
 'ALEXANDRA RD': 270,
 'CHIN SWEE RD': 271,
 'SIMS PL': 272,
 'HOUGANG AVE 2': 273,
 'HOUGANG AVE 8': 274,
 'SEMBAWANG RD': 275,
 'SIMEI ST 1': 276,
 'BT BATOK ST 34': 277,
 'BT MERAH CTRL': 278,
 'LIM LIAK ST': 279,
 'JLN TENTERAM': 280,
 'WOODLANDS ST 32': 281,
 'SIN MING AVE': 282,
 'BT BATOK ST 52': 283,
 'DELTA AVE': 284,
 'PIPIT RD': 285,
 'HOUGANG AVE 4': 286,
 'QUEENSWAY': 287,
 'YISHUN ST 61': 288,
 'BISHAN ST 12': 289,
 "JLN MA'MOR": 290,
 'TAMPINES ST 44': 291,
 'TAMPINES ST 43': 292,
 'BISHAN ST 13': 293,
 'JLN DUSUN': 294,
 'YISHUN AVE 2': 295,
 'JOO CHIAT RD': 296,
 'EAST COAST RD': 297,
 'REDHILL RD': 298,
 'KIM PONG RD': 299,
 'RACE COURSE RD': 300,
 'KRETA AYER RD': 301,
 'HOUGANG ST 61': 302,
 'TESSENSOHN RD': 303,
 'MARSILING RD': 304,
 'YISHUN ST 81': 305,
 'BT BATOK ST 51': 306,
 'BT BATOK WEST AVE 4': 307,
 'BT BATOK WEST AVE 2': 308,
 'JURONG WEST ST 91': 309,
 'JURONG WEST ST 81': 310,
 'GANGSA RD': 311,
 'MCNAIR RD': 312,
 'SIMEI ST 4': 313,
 'YISHUN AVE 7': 314,
 'SERANGOON NTH AVE 2': 315,
 'YISHUN AVE 11': 316,
 'BANGKIT RD': 317,
 'JURONG WEST ST 73': 318,
 'OUTRAM HILL': 319,
 'HOUGANG AVE 6': 320,
 'PASIR RIS ST 12': 321,
 'PENDING RD': 322,
 'PETIR RD': 323,
 'LOR 3 GEYLANG': 324,
 'BISHAN ST 11': 325,
 'PASIR RIS DR 6': 326,
 'BISHAN ST 23': 327,
 'JURONG WEST ST 92': 328,
 'PASIR RIS ST 11': 329,
 'YISHUN CTRL': 330,
 'BISHAN ST 22': 331,
 'SIMEI RD': 332,
 'TAMPINES ST 84': 333,
 'BT PANJANG RING RD': 334,
 'JURONG WEST ST 93': 335,
 'FAJAR RD': 336,
 'WOODLANDS ST 81': 337,
 'CHOA CHU KANG CTRL': 338,
 'PASIR RIS ST 51': 339,
 'HOUGANG ST 52': 340,
 'CASHEW RD': 341,
 'TOH YI DR': 342,
 'HOUGANG CTRL': 343,
 'KG KAYU RD': 344,
 'TAMPINES AVE 8': 345,
 'TAMPINES ST 45': 346,
 'SIMEI ST 2': 347,
 'WOODLANDS AVE 3': 348,
 'LENGKONG TIGA': 349,
 'WOODLANDS ST 82': 350,
 'SERANGOON NTH AVE 4': 351,
 'SERANGOON CTRL DR': 352,
 'BRIGHT HILL DR': 353,
 'SAUJANA RD': 354,
 'CHOA CHU KANG AVE 3': 355,
 'TAMPINES AVE 9': 356,
 'JURONG WEST ST 51': 357,
 'YUNG HO RD': 358,
 'SERANGOON AVE 1': 359,
 'PASIR RIS ST 41': 360,
 'GEYLANG EAST AVE 2': 361,
 'CHOA CHU KANG AVE 2': 362,
 'KIM KEAT LINK': 363,
 'PASIR RIS DR 4': 364,
 'PASIR RIS ST 21': 365,
 'SENG POH RD': 366,
 'HOUGANG ST 51': 367,
 'JURONG WEST ST 72': 368,
 'JURONG WEST ST 71': 369,
 'PASIR RIS ST 52': 370,
 'TAMPINES ST 32': 371,
 'CHOA CHU KANG AVE 4': 372,
 'CHOA CHU KANG LOOP': 373,
 'JLN TENAGA': 374,
 'TAMPINES CTRL 1': 375,
 'TAMPINES ST 33': 376,
 'BT BATOK WEST AVE 7': 377,
 'JURONG WEST AVE 5': 378,
 'TAMPINES AVE 7': 379,
 'WOODLANDS ST 83': 380,
 'CHOA CHU KANG ST 51': 381,
 'PASIR RIS DR 3': 382,
 'YISHUN CTRL 1': 383,
 'CHOA CHU KANG AVE 1': 384,
 'WOODLANDS ST 31': 385,
 'BT MERAH LANE 1': 386,
 'PASIR RIS ST 13': 387,
 'ELIAS RD': 388,
 'BISHAN ST 24': 389,
 'WHAMPOA RD': 390,
 'WOODLANDS ST 41': 391,
 'PASIR RIS ST 71': 392,
 'JURONG WEST ST 74': 393,
 'PASIR RIS DR 1': 394,
 'PASIR RIS ST 72': 395,
 'PASIR RIS DR 10': 396,
 'CHOA CHU KANG ST 52': 397,
 'CLARENCE LANE': 398,
 'CHOA CHU KANG NTH 6': 399,
 'PASIR RIS ST 53': 400,
 'CHOA CHU KANG NTH 5': 401,
 'ANG MO KIO ST 21': 402,
 'JLN DAMAI': 403,
 'CHOA CHU KANG ST 62': 404,
 'WOODLANDS AVE 5': 405,
 'WOODLANDS DR 50': 406,
 'CHOA CHU KANG ST 53': 407,
 'TAMPINES ST 72': 408,
 'UPP SERANGOON RD': 409,
 'JURONG WEST ST 75': 410,
 'STRATHMORE AVE': 411,
 'ANG MO KIO ST 31': 412,
 'TAMPINES ST 34': 413,
 'YUNG AN RD': 414,
 'WOODLANDS AVE 4': 415,
 'CHOA CHU KANG NTH 7': 416,
 'ANG MO KIO ST 11': 417,
 'WOODLANDS AVE 9': 418,
 'YUNG LOH RD': 419,
 'CHOA CHU KANG DR': 420,
 'CHOA CHU KANG ST 54': 421,
 'REDHILL LANE': 422,
 'KANG CHING RD': 423,
 'TAH CHING RD': 424,
 'SIMEI ST 5': 425,
 'WOODLANDS DR 40': 426,
 'WOODLANDS DR 70': 427,
 'TAMPINES ST 71': 428,
 'WOODLANDS DR 42': 429,
 'SERANGOON NTH AVE 3': 430,
 'JELAPANG RD': 431,
 'BT BATOK ST 22': 432,
 'HOUGANG ST 91': 433,
 'WOODLANDS AVE 6': 434,
 'WOODLANDS CIRCLE': 435,
 'CORPORATION DR': 436,
 'LOMPANG RD': 437,
 'WOODLANDS DR 72': 438,
 'CHOA CHU KANG ST 64': 439,
 'BT BATOK ST 24': 440,
 'JLN TECK WHYE': 441,
 'WOODLANDS CRES': 442,
 'WOODLANDS DR 60': 443,
 'CHANGI VILLAGE RD': 444,
 'BT BATOK ST 25': 445,
 'HOUGANG AVE 9': 446,
 'JURONG WEST CTRL 1': 447,
 'WOODLANDS RING RD': 448,
 'CHOA CHU KANG AVE 5': 449,
 'TOH GUAN RD': 450,
 'JURONG WEST ST 61': 451,
 'WOODLANDS DR 14': 452,
 'HOUGANG ST 92': 453,
 'CHOA CHU KANG CRES': 454,
 'SEMBAWANG CL': 455,
 'CANBERRA RD': 456,
 'SEMBAWANG CRES': 457,
 'SEMBAWANG VISTA': 458,
 'COMPASSVALE WALK': 459,
 'RIVERVALE ST': 460,
 'WOODLANDS DR 62': 461,
 'SEMBAWANG DR': 462,
 'WOODLANDS DR 53': 463,
 'WOODLANDS DR 52': 464,
 'RIVERVALE WALK': 465,
 'COMPASSVALE LANE': 466,
 'RIVERVALE DR': 467,
 'SENJA RD': 468,
 'JURONG WEST ST 65': 469,
 'RIVERVALE CRES': 470,
 'WOODLANDS DR 44': 471,
 'COMPASSVALE DR': 472,
 'WOODLANDS DR 16': 473,
 'COMPASSVALE RD': 474,
 'WOODLANDS DR 73': 475,
 'HOUGANG ST 31': 476,
 'JURONG WEST ST 64': 477,
 'WOODLANDS DR 71': 478,
 'YISHUN ST 20': 479,
 'ADMIRALTY DR': 480,
 'COMPASSVALE ST': 481,
 'BEDOK RESERVOIR VIEW': 482,
 'YUNG SHENG RD': 483,
 'ADMIRALTY LINK': 484,
 'SENGKANG EAST WAY': 485,
 'ANG MO KIO ST 32': 486,
 'ANG MO KIO ST 52': 487,
 'BOON TIONG RD': 488,
 'JURONG WEST ST 62': 489,
 'ANCHORVALE LINK': 490,
 'CANBERRA LINK': 491,
 'COMPASSVALE CRES': 492,
 'CLEMENTI ST 12': 493,
 'MONTREAL DR': 494,
 'WELLINGTON CIRCLE': 495,
 'SENGKANG EAST RD': 496,
 'JURONG WEST AVE 3': 497,
 'ANCHORVALE LANE': 498,
 'SENJA LINK': 499,
 'EDGEFIELD PLAINS': 500,
 'ANCHORVALE DR': 501,
 'SEGAR RD': 502,
 'FARRER PK RD': 503,
 'PUNGGOL FIELD': 504,
 'EDGEDALE PLAINS': 505,
 'ANCHORVALE RD': 506,
 'CANTONMENT CL': 507,
 'JLN MEMBINA': 508,
 'FERNVALE LANE': 509,
 'JURONG WEST ST 25': 510,
 'CLEMENTI ST 11': 511,
 'PUNGGOL FIELD WALK': 512,
 'KLANG LANE': 513,
 'PUNGGOL CTRL': 514,
 'JELEBU RD': 515,
 'BUANGKOK CRES': 516,
 'WOODLANDS DR 75': 517,
 'BT BATOK WEST AVE 5': 518,
 'JELLICOE RD': 519,
 'PUNGGOL DR': 520,
 'JURONG WEST ST 24': 521,
 'SEMBAWANG WAY': 522,
 'FERNVALE RD': 523,
 'BUANGKOK LINK': 524,
 'FERNVALE LINK': 525,
 'JLN TIGA': 526,
 'YUAN CHING RD': 527,
 'COMPASSVALE LINK': 528,
 'MARINE PARADE CTRL': 529,
 'COMPASSVALE BOW': 530,
 'PUNGGOL RD': 531,
 'BEDOK CTRL': 532,
 'PUNGGOL EAST': 533,
 'SENGKANG CTRL': 534,
 'TAMPINES CTRL 7': 535,
 'SENGKANG WEST AVE': 536,
 'PUNGGOL PL': 537,
 'CANTONMENT RD': 538,
 'GHIM MOH LINK': 539,
 'SIMEI LANE': 540,
 'YISHUN ST 41': 541,
 'TELOK BLANGAH ST 31': 542,
 'JLN KAYU': 543,
 'LOR 1A TOA PAYOH': 544,
 'PUNGGOL WALK': 545,
 'SENGKANG WEST WAY': 546,
 'BUANGKOK GREEN': 547,
 'PUNGGOL WAY': 548,
 'YISHUN ST 31': 549,
 'TECK WHYE CRES': 550,
 'MONTREAL LINK': 551,
 'UPP SERANGOON CRES': 552,
 'SUMANG LINK': 553,
 'SENGKANG EAST AVE': 554,
 'YISHUN AVE 1': 555,
 'ANCHORVALE CRES': 556,
 'ANCHORVALE ST': 557,
 'TAMPINES CTRL 8': 558,
 'YISHUN ST 51': 559,
 'UPP SERANGOON VIEW': 560,
 'TAMPINES AVE 1': 561,
 'BEDOK RESERVOIR CRES': 562,
 'ANG MO KIO ST 61': 563,
 'DAWSON RD': 564,
 'FERNVALE ST': 565,
 'HOUGANG ST 32': 566,
 'TAMPINES ST 86': 567,
 'SUMANG WALK': 568,
 'CHOA CHU KANG AVE 7': 569,
 'KEAT HONG CL': 570,
 'JURONG WEST CTRL 3': 571,
 'KEAT HONG LINK': 572,
 'ALJUNIED AVE 2': 573,
 'CANBERRA CRES': 574,
 'SUMANG LANE': 575,
 'CANBERRA ST': 576,
 'ANG MO KIO ST 44': 577,
 'WOODLANDS RISE': 578,
 'CANBERRA WALK': 579,
 'ANG MO KIO ST 51': 580,
 'BT BATOK EAST AVE 6': 581,
 'BT BATOK WEST AVE 9': 582,
 'TAMPINES ST 61': 583}

In [14]:
# alter the column with the mapped numbers
combined_df['street_name'] = combined_df['street_name'].map(streets_mapping)

# Display the DataFrame
combined_df

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease
0,1990-01,ANG MO KIO,1 ROOM,309,1,10 TO 12,31.0,IMPROVED,1977,9000.0,NaN
1,1990-01,ANG MO KIO,1 ROOM,309,1,04 TO 06,31.0,IMPROVED,1977,6000.0,NaN
2,1990-01,ANG MO KIO,1 ROOM,309,1,10 TO 12,31.0,IMPROVED,1977,8000.0,NaN
3,1990-01,ANG MO KIO,1 ROOM,309,1,07 TO 09,31.0,IMPROVED,1977,6000.0,NaN
4,1990-01,ANG MO KIO,3 ROOM,216,1,04 TO 06,73.0,NEW GENERATION,1976,47200.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
912886,2023-05,YISHUN,EXECUTIVE,827,305,01 TO 03,154.0,Maisonette,1987,829000.0,63 years 06 months
912887,2023-05,YISHUN,EXECUTIVE,824,305,07 TO 09,146.0,Maisonette,1987,855000.0,63 years 06 months
912888,2023-07,YISHUN,EXECUTIVE,837,305,01 TO 03,146.0,Maisonette,1988,860000.0,63 years 07 months
912889,2023-01,YISHUN,MULTI-GENERATION,666,259,07 TO 09,179.0,Multi Generation,1987,1080000.0,63 years 11 months
912890,2023-06,YISHUN,MULTI-GENERATION,633,288,04 TO 06,159.0,Multi Generation,1987,935000.0,63 years 06 months

In [15]:
# function to convert the years and months to years in decimal
def convert_to_years(row):
    if pd.notna(row):
        if isinstance(row, str):
            if 'years' in row:
                parts = row.split()
                years = float(parts[0])
                if len(parts) > 2:  # If there's a month part as well
                    months = float(parts[2])
                    return years + months / 12
                else:
                    return years
        else:
          return row
    return row

In [16]:
# Apply the conversion function to the DataFrame column
combined_df['remaining_lease'] = combined_df['remaining_lease'].apply(convert_to_years)
combined_df

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease
0,1990-01,ANG MO KIO,1 ROOM,309,1,10 TO 12,31.0,IMPROVED,1977,9000.0,NaN
1,1990-01,ANG MO KIO,1 ROOM,309,1,04 TO 06,31.0,IMPROVED,1977,6000.0,NaN
2,1990-01,ANG MO KIO,1 ROOM,309,1,10 TO 12,31.0,IMPROVED,1977,8000.0,NaN
3,1990-01,ANG MO KIO,1 ROOM,309,1,07 TO 09,31.0,IMPROVED,1977,6000.0,NaN
4,1990-01,ANG MO KIO,3 ROOM,216,1,04 TO 06,73.0,NEW GENERATION,1976,47200.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
912886,2023-05,YISHUN,EXECUTIVE,827,305,01 TO 03,154.0,Maisonette,1987,829000.0,63.500000
912887,2023-05,YISHUN,EXECUTIVE,824,305,07 TO 09,146.0,Maisonette,1987,855000.0,63.500000
912888,2023-07,YISHUN,EXECUTIVE,837,305,01 TO 03,146.0,Maisonette,1988,860000.0,63.583333
912889,2023-01,YISHUN,MULTI-GENERATION,666,259,07 TO 09,179.0,Multi Generation,1987,1080000.0,63.916667
912890,2023-06,YISHUN,MULTI-GENERATION,633,288,04 TO 06,159.0,Multi Generation,1987,935000.0,63.500000

In [17]:
# fill null values in remaining_lease with its mode
combined_df['remaining_lease']= combined_df['remaining_lease'].fillna(combined_df['remaining_lease'].mode()[0])
combined_df

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease
0,1990-01,ANG MO KIO,1 ROOM,309,1,10 TO 12,31.0,IMPROVED,1977,9000.0,68.000000
1,1990-01,ANG MO KIO,1 ROOM,309,1,04 TO 06,31.0,IMPROVED,1977,6000.0,68.000000
2,1990-01,ANG MO KIO,1 ROOM,309,1,10 TO 12,31.0,IMPROVED,1977,8000.0,68.000000
3,1990-01,ANG MO KIO,1 ROOM,309,1,07 TO 09,31.0,IMPROVED,1977,6000.0,68.000000
4,1990-01,ANG MO KIO,3 ROOM,216,1,04 TO 06,73.0,NEW GENERATION,1976,47200.0,68.000000
...,...,...,...,...,...,...,...,...,...,...,...
912886,2023-05,YISHUN,EXECUTIVE,827,305,01 TO 03,154.0,Maisonette,1987,829000.0,63.500000
912887,2023-05,YISHUN,EXECUTIVE,824,305,07 TO 09,146.0,Maisonette,1987,855000.0,63.500000
912888,2023-07,YISHUN,EXECUTIVE,837,305,01 TO 03,146.0,Maisonette,1988,860000.0,63.583333
912889,2023-01,YISHUN,MULTI-GENERATION,666,259,07 TO 09,179.0,Multi Generation,1987,1080000.0,63.916667
912890,2023-06,YISHUN,MULTI-GENERATION,633,288,04 TO 06,159.0,Multi Generation,1987,935000.0,63.500000

In [18]:
# Split the 'Range' column into lower and upper bounds
combined_df[['storey_lower_bound', 'storey_upper_bound']] = combined_df['storey_range'].str.split(' TO ', expand=True)

# Convert the lower and upper bounds to numeric values
combined_df['storey_lower_bound'] = pd.to_numeric(combined_df['storey_lower_bound'])
combined_df['storey_upper_bound'] = pd.to_numeric(combined_df['storey_upper_bound'])

combined_df

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease,storey_lower_bound,storey_upper_bound
0,1990-01,ANG MO KIO,1 ROOM,309,1,10 TO 12,31.0,IMPROVED,1977,9000.0,68.000000,10,12
1,1990-01,ANG MO KIO,1 ROOM,309,1,04 TO 06,31.0,IMPROVED,1977,6000.0,68.000000,4,6
2,1990-01,ANG MO KIO,1 ROOM,309,1,10 TO 12,31.0,IMPROVED,1977,8000.0,68.000000,10,12
3,1990-01,ANG MO KIO,1 ROOM,309,1,07 TO 09,31.0,IMPROVED,1977,6000.0,68.000000,7,9
4,1990-01,ANG MO KIO,3 ROOM,216,1,04 TO 06,73.0,NEW GENERATION,1976,47200.0,68.000000,4,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
912886,2023-05,YISHUN,EXECUTIVE,827,305,01 TO 03,154.0,Maisonette,1987,829000.0,63.500000,1,3
912887,2023-05,YISHUN,EXECUTIVE,824,305,07 TO 09,146.0,Maisonette,1987,855000.0,63.500000,7,9
912888,2023-07,YISHUN,EXECUTIVE,837,305,01 TO 03,146.0,Maisonette,1988,860000.0,63.583333,1,3
912889,2023-01,YISHUN,MULTI-GENERATION,666,259,07 TO 09,179.0,Multi Generation,1987,1080000.0,63.916667,7,9
912890,2023-06,YISHUN,MULTI-GENERATION,633,288,04 TO 06,159.0,Multi Generation,1987,935000.0,63.500000,4,6

In [19]:
# drop storey range column
combined_df.drop('storey_range', axis=1, inplace=True)
combined_df

,month,town,flat_type,block,street_name,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease,storey_lower_bound,storey_upper_bound
0,1990-01,ANG MO KIO,1 ROOM,309,1,31.0,IMPROVED,1977,9000.0,68.000000,10,12
1,1990-01,ANG MO KIO,1 ROOM,309,1,31.0,IMPROVED,1977,6000.0,68.000000,4,6
2,1990-01,ANG MO KIO,1 ROOM,309,1,31.0,IMPROVED,1977,8000.0,68.000000,10,12
3,1990-01,ANG MO KIO,1 ROOM,309,1,31.0,IMPROVED,1977,6000.0,68.000000,7,9
4,1990-01,ANG MO KIO,3 ROOM,216,1,73.0,NEW GENERATION,1976,47200.0,68.000000,4,6
...,...,...,...,...,...,...,...,...,...,...,...,...
912886,2023-05,YISHUN,EXECUTIVE,827,305,154.0,Maisonette,1987,829000.0,63.500000,1,3
912887,2023-05,YISHUN,EXECUTIVE,824,305,146.0,Maisonette,1987,855000.0,63.500000,7,9
912888,2023-07,YISHUN,EXECUTIVE,837,305,146.0,Maisonette,1988,860000.0,63.583333,1,3
912889,2023-01,YISHUN,MULTI-GENERATION,666,259,179.0,Multi Generation,1987,1080000.0,63.916667,7,9
912890,2023-06,YISHUN,MULTI-GENERATION,633,288,159.0,Multi Generation,1987,935000.0,63.500000,4,6

In [20]:
# list unique flat type
combined_df['flat_type'].unique()

array(['1 ROOM', '3 ROOM', '4 ROOM', '5 ROOM', '2 ROOM', 'EXECUTIVE',
       'MULTI GENERATION', 'MULTI-GENERATION'], dtype=object)

In [21]:
# Replace 'MULTI-GENERATION' with 'MULTI GENERATION' in the specified column to avoid duplicate
combined_df['flat_type'] = combined_df['flat_type'].str.replace('MULTI-GENERATION', 'MULTI GENERATION')

In [22]:
# list unique flat type
combined_df['flat_type'].unique()

array(['1 ROOM', '3 ROOM', '4 ROOM', '5 ROOM', '2 ROOM', 'EXECUTIVE',
       'MULTI GENERATION'], dtype=object)

In [23]:
# Define a mapping of flat_type to numbers
category_mapping = {
    '1 ROOM': 1,
    '2 ROOM': 2,
    '3 ROOM': 3,
    '4 ROOM': 4,
    '5 ROOM': 5,
    'EXECUTIVE': 6,
    'MULTI GENERATION': 7
}

# alter the column with the mapped numbers
combined_df['flat_type'] = combined_df['flat_type'].map(category_mapping)

# Display the DataFrame
combined_df

,month,town,flat_type,block,street_name,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease,storey_lower_bound,storey_upper_bound
0,1990-01,ANG MO KIO,1,309,1,31.0,IMPROVED,1977,9000.0,68.000000,10,12
1,1990-01,ANG MO KIO,1,309,1,31.0,IMPROVED,1977,6000.0,68.000000,4,6
2,1990-01,ANG MO KIO,1,309,1,31.0,IMPROVED,1977,8000.0,68.000000,10,12
3,1990-01,ANG MO KIO,1,309,1,31.0,IMPROVED,1977,6000.0,68.000000,7,9
4,1990-01,ANG MO KIO,3,216,1,73.0,NEW GENERATION,1976,47200.0,68.000000,4,6
...,...,...,...,...,...,...,...,...,...,...,...,...
912886,2023-05,YISHUN,6,827,305,154.0,Maisonette,1987,829000.0,63.500000,1,3
912887,2023-05,YISHUN,6,824,305,146.0,Maisonette,1987,855000.0,63.500000,7,9
912888,2023-07,YISHUN,6,837,305,146.0,Maisonette,1988,860000.0,63.583333,1,3
912889,2023-01,YISHUN,7,666,259,179.0,Multi Generation,1987,1080000.0,63.916667,7,9
912890,2023-06,YISHUN,7,633,288,159.0,Multi Generation,1987,935000.0,63.500000,4,6

In [24]:
# list unique flat model
combined_df['flat_model'].unique()

array(['IMPROVED', 'NEW GENERATION', 'MODEL A', 'STANDARD', 'SIMPLIFIED',
       'MODEL A-MAISONETTE', 'APARTMENT', 'MAISONETTE', 'TERRACE',
       '2-ROOM', 'IMPROVED-MAISONETTE', 'MULTI GENERATION',
       'PREMIUM APARTMENT', 'Improved', 'New Generation', 'Model A',
       'Standard', 'Apartment', 'Simplified', 'Model A-Maisonette',
       'Maisonette', 'Multi Generation', 'Adjoined flat',
       'Premium Apartment', 'Terrace', 'Improved-Maisonette',
       'Premium Maisonette', '2-room', 'Model A2', 'DBSS', 'Type S1',
       'Type S2', 'Premium Apartment Loft', '3Gen'], dtype=object)

In [25]:
# Create a mapping of 'flat_model' values to numbers
flat_model_mapping = {
    'IMPROVED': 1,
    'NEW GENERATION': 2,
    'MODEL A': 3,
    'STANDARD': 4,
    'SIMPLIFIED': 5,
    'MODEL A-MAISONETTE': 6,
    'APARTMENT': 7,
    'MAISONETTE': 8,
    'TERRACE': 9,
    '2-ROOM': 10,
    'IMPROVED-MAISONETTE': 11,
    'MULTI GENERATION': 12,
    'PREMIUM APARTMENT': 13,
    'Improved': 14,
    'New Generation': 15,
    'Model A': 16,
    'Standard': 17,
    'Apartment': 18,
    'Simplified': 19,
    'Model A-Maisonette': 20,
    'Maisonette': 21,
    'Multi Generation': 22,
    'Adjoined flat': 23,
    'Premium Apartment': 24,
    'Terrace': 25,
    'Improved-Maisonette': 26,
    'Premium Maisonette': 27,
    '2-room': 28,
    'Model A2': 29,
    'DBSS': 30,
    'Type S1': 31,
    'Type S2': 32,
    'Premium Apartment Loft': 33,
    '3Gen': 34
}

# Map 'flat_model' values to numbers
combined_df['flat_model'] = combined_df['flat_model'].map(flat_model_mapping)

# Display the DataFrame
combined_df

,month,town,flat_type,block,street_name,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease,storey_lower_bound,storey_upper_bound
0,1990-01,ANG MO KIO,1,309,1,31.0,1,1977,9000.0,68.000000,10,12
1,1990-01,ANG MO KIO,1,309,1,31.0,1,1977,6000.0,68.000000,4,6
2,1990-01,ANG MO KIO,1,309,1,31.0,1,1977,8000.0,68.000000,10,12
3,1990-01,ANG MO KIO,1,309,1,31.0,1,1977,6000.0,68.000000,7,9
4,1990-01,ANG MO KIO,3,216,1,73.0,2,1976,47200.0,68.000000,4,6
...,...,...,...,...,...,...,...,...,...,...,...,...
912886,2023-05,YISHUN,6,827,305,154.0,21,1987,829000.0,63.500000,1,3
912887,2023-05,YISHUN,6,824,305,146.0,21,1987,855000.0,63.500000,7,9
912888,2023-07,YISHUN,6,837,305,146.0,21,1988,860000.0,63.583333,1,3
912889,2023-01,YISHUN,7,666,259,179.0,22,1987,1080000.0,63.916667,7,9
912890,2023-06,YISHUN,7,633,288,159.0,22,1987,935000.0,63.500000,4,6

In [26]:
# list unique town names
combined_df['town'].unique()

array(['ANG MO KIO', 'BEDOK', 'BISHAN', 'BUKIT BATOK', 'BUKIT MERAH',
       'BUKIT TIMAH', 'CENTRAL AREA', 'CHOA CHU KANG', 'CLEMENTI',
       'GEYLANG', 'HOUGANG', 'JURONG EAST', 'JURONG WEST',
       'KALLANG/WHAMPOA', 'MARINE PARADE', 'QUEENSTOWN', 'SENGKANG',
       'SERANGOON', 'TAMPINES', 'TOA PAYOH', 'WOODLANDS', 'YISHUN',
       'LIM CHU KANG', 'SEMBAWANG', 'BUKIT PANJANG', 'PASIR RIS',
       'PUNGGOL'], dtype=object)

In [27]:
# Create a mapping of 'town' values to numbers
town_mapping = {
    'ANG MO KIO': 1,
    'BEDOK': 2,
    'BISHAN': 3,
    'BUKIT BATOK': 4,
    'BUKIT MERAH': 5,
    'BUKIT TIMAH': 6,
    'CENTRAL AREA': 7,
    'CHOA CHU KANG': 8,
    'CLEMENTI': 9,
    'GEYLANG': 10,
    'HOUGANG': 11,
    'JURONG EAST': 12,
    'JURONG WEST': 13,
    'KALLANG/WHAMPOA': 14,
    'MARINE PARADE': 15,
    'QUEENSTOWN': 16,
    'SENGKANG': 17,
    'SERANGOON': 18,
    'TAMPINES': 19,
    'TOA PAYOH': 20,
    'WOODLANDS': 21,
    'YISHUN': 22,
    'LIM CHU KANG': 23,
    'SEMBAWANG': 24,
    'BUKIT PANJANG': 25,
    'PASIR RIS': 26,
    'PUNGGOL': 27
}

# Map 'town' values to numbers
combined_df['town'] = combined_df['town'].map(town_mapping)

# Display the DataFrame
combined_df

,month,town,flat_type,block,street_name,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease,storey_lower_bound,storey_upper_bound
0,1990-01,1,1,309,1,31.0,1,1977,9000.0,68.000000,10,12
1,1990-01,1,1,309,1,31.0,1,1977,6000.0,68.000000,4,6
2,1990-01,1,1,309,1,31.0,1,1977,8000.0,68.000000,10,12
3,1990-01,1,1,309,1,31.0,1,1977,6000.0,68.000000,7,9
4,1990-01,1,3,216,1,73.0,2,1976,47200.0,68.000000,4,6
...,...,...,...,...,...,...,...,...,...,...,...,...
912886,2023-05,22,6,827,305,154.0,21,1987,829000.0,63.500000,1,3
912887,2023-05,22,6,824,305,146.0,21,1987,855000.0,63.500000,7,9
912888,2023-07,22,6,837,305,146.0,21,1988,860000.0,63.583333,1,3
912889,2023-01,22,7,666,259,179.0,22,1987,1080000.0,63.916667,7,9
912890,2023-06,22,7,633,288,159.0,22,1987,935000.0,63.500000,4,6

In [28]:
# Define a mapping for letters to decimal values
letter_mapping = {chr(ord('A') + i): f'.{i+1}' for i in range(26)}

# Replace letters with their corresponding decimal values
for letter, decimal in letter_mapping.items():
    combined_df['block'] = combined_df['block'].str.replace(letter, decimal)

# Use pd.to_numeric to convert the column to float and set invalid parsing to NaN
combined_df['block'] = pd.to_numeric(combined_df['block'])

# Display the DataFrame with the column as float values
combined_df

,month,town,flat_type,block,street_name,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease,storey_lower_bound,storey_upper_bound
0,1990-01,1,1,309.0,1,31.0,1,1977,9000.0,68.000000,10,12
1,1990-01,1,1,309.0,1,31.0,1,1977,6000.0,68.000000,4,6
2,1990-01,1,1,309.0,1,31.0,1,1977,8000.0,68.000000,10,12
3,1990-01,1,1,309.0,1,31.0,1,1977,6000.0,68.000000,7,9
4,1990-01,1,3,216.0,1,73.0,2,1976,47200.0,68.000000,4,6
...,...,...,...,...,...,...,...,...,...,...,...,...
912886,2023-05,22,6,827.0,305,154.0,21,1987,829000.0,63.500000,1,3
912887,2023-05,22,6,824.0,305,146.0,21,1987,855000.0,63.500000,7,9
912888,2023-07,22,6,837.0,305,146.0,21,1988,860000.0,63.583333,1,3
912889,2023-01,22,7,666.0,259,179.0,22,1987,1080000.0,63.916667,7,9
912890,2023-06,22,7,633.0,288,159.0,22,1987,935000.0,63.500000,4,6

In [29]:
# check datatype of the lease resale month column
month = combined_df['month'].dtype
month

dtype('O')

In [30]:
# Separate the year and month of resale
combined_df[['resale_year', 'resale_month']] = combined_df['month'].str.split('-', expand=True)
combined_df

,month,town,flat_type,block,street_name,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease,storey_lower_bound,storey_upper_bound,resale_year,resale_month
0,1990-01,1,1,309.0,1,31.0,1,1977,9000.0,68.000000,10,12,1990,01
1,1990-01,1,1,309.0,1,31.0,1,1977,6000.0,68.000000,4,6,1990,01
2,1990-01,1,1,309.0,1,31.0,1,1977,8000.0,68.000000,10,12,1990,01
3,1990-01,1,1,309.0,1,31.0,1,1977,6000.0,68.000000,7,9,1990,01
4,1990-01,1,3,216.0,1,73.0,2,1976,47200.0,68.000000,4,6,1990,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912886,2023-05,22,6,827.0,305,154.0,21,1987,829000.0,63.500000,1,3,2023,05
912887,2023-05,22,6,824.0,305,146.0,21,1987,855000.0,63.500000,7,9,2023,05
912888,2023-07,22,6,837.0,305,146.0,21,1988,860000.0,63.583333,1,3,2023,07
912889,2023-01,22,7,666.0,259,179.0,22,1987,1080000.0,63.916667,7,9,2023,01
912890,2023-06,22,7,633.0,288,159.0,22,1987,935000.0,63.500000,4,6,2023,06

In [31]:
# drop the resale month column
combined_df.drop('month', axis = 1, inplace= True)
combined_df

,town,flat_type,block,street_name,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease,storey_lower_bound,storey_upper_bound,resale_year,resale_month
0,1,1,309.0,1,31.0,1,1977,9000.0,68.000000,10,12,1990,01
1,1,1,309.0,1,31.0,1,1977,6000.0,68.000000,4,6,1990,01
2,1,1,309.0,1,31.0,1,1977,8000.0,68.000000,10,12,1990,01
3,1,1,309.0,1,31.0,1,1977,6000.0,68.000000,7,9,1990,01
4,1,3,216.0,1,73.0,2,1976,47200.0,68.000000,4,6,1990,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
912886,22,6,827.0,305,154.0,21,1987,829000.0,63.500000,1,3,2023,05
912887,22,6,824.0,305,146.0,21,1987,855000.0,63.500000,7,9,2023,05
912888,22,6,837.0,305,146.0,21,1988,860000.0,63.583333,1,3,2023,07
912889,22,7,666.0,259,179.0,22,1987,1080000.0,63.916667,7,9,2023,01
912890,22,7,633.0,288,159.0,22,1987,935000.0,63.500000,4,6,2023,06

In [32]:
# check for null values
combined_df.isnull().sum()

town                   0
flat_type              0
block                  0
street_name            0
floor_area_sqm         0
flat_model             0
lease_commence_date    0
resale_price           0
remaining_lease        0
storey_lower_bound     0
storey_upper_bound     0
resale_year            0
resale_month           0
dtype: int64

In [33]:
# fetch sample data
c_df = combined_df.sample(n=100000, random_state=42)

In [34]:
# assign feature and target variable
X = c_df.drop('resale_price', axis= 1)
y = c_df['resale_price']

In [35]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# X_train and y_train will be your training data, and X_test and y_test will be your testing data.

In [36]:
# Create and train the Random Forest Regressor model
rf_regressor = RandomForestRegressor(random_state=42)
rf_regressor.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf_regressor.predict(X_test)

# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(y_test, y_pred)

# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)

# Calculate Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)

# Calculate R-squared (R2) Score
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error (MAE)    :", mae)
print("Mean Squared Error (MSE)     :", mse)
print("Root Mean Square Error (RMSE):", rmse)
print("R-squared (R2) Score         :", r2)

Mean Absolute Error (MAE)    : 19311.347102162148
Mean Squared Error (MSE)     : 876488712.5099463
Root Mean Square Error (RMSE): 29605.552055483553
R-squared (R2) Score         : 0.969513812488633

In [37]:
# get sample to predict the resale price
pre_df = combined_df.sample(n=2)
pre_df

,town,flat_type,block,street_name,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease,storey_lower_bound,storey_upper_bound,resale_year,resale_month
319512,2,4,550.0,25,93.0,15,1980,235000.0,68.0,7,9,2000,12
281974,8,4,543.0,397,107.0,3,1994,280000.0,68.0,7,9,1999,11

In [38]:
# drop the resale price column
A = pre_df.drop('resale_price', axis = 1)

In [39]:
# Make predictions on the sample
pre_pred = rf_regressor.predict(A)
pre_pred

array([238110., 279520.])

In [40]:
# save the processed data for the deployment
combined_df.to_csv('c.csv')